// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: internal/cache/cache.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CacheFile is the top-level container for persisted cache entries.
type CacheFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CacheEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheFile) Reset() {
	*x = CacheFile{}
	mi := &file_internal_cache_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheFile) ProtoMessage() {}

func (x *CacheFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheFile.ProtoReflect.Descriptor instead.
func (*CacheFile) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheFile) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// CacheEntry represents a single key-value pair with expiration.
type CacheEntry struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Key          string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpirationNs int64                  `protobuf:"varint,2,opt,name=expiration_ns,json=expirationNs,proto3" json:"expiration_ns,omitempty"` // Unix nano timestamp, 0 = no expiry
	// Value type discriminator — exactly one should be set.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*CacheEntry_StringValue
	//	*CacheEntry_BoolValue
	//	*CacheEntry_StringList
	//	*CacheEntry_FileContent
	//	*CacheEntry_GithubTree
	//	*CacheEntry_NpmPackage
	//	*CacheEntry_BytesValue
	Value         isCacheEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_internal_cache_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheEntry) GetExpirationNs() int64 {
	if x != nil {
		return x.ExpirationNs
	}
	return 0
}

func (x *CacheEntry) GetValue() isCacheEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CacheEntry) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *CacheEntry) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *CacheEntry) GetStringList() *StringList {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_StringList); ok {
			return x.StringList
		}
	}
	return nil
}

func (x *CacheEntry) GetFileContent() *FileContent {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_FileContent); ok {
			return x.FileContent
		}
	}
	return nil
}

func (x *CacheEntry) GetGithubTree() *GitHubTree {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_GithubTree); ok {
			return x.GithubTree
		}
	}
	return nil
}

func (x *CacheEntry) GetNpmPackage() *NpmPackage {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_NpmPackage); ok {
			return x.NpmPackage
		}
	}
	return nil
}

func (x *CacheEntry) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*CacheEntry_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isCacheEntry_Value interface {
	isCacheEntry_Value()
}

type CacheEntry_StringValue struct {
	StringValue string `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type CacheEntry_BoolValue struct {
	BoolValue bool `protobuf:"varint,11,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type CacheEntry_StringList struct {
	StringList *StringList `protobuf:"bytes,12,opt,name=string_list,json=stringList,proto3,oneof"`
}

type CacheEntry_FileContent struct {
	FileContent *FileContent `protobuf:"bytes,13,opt,name=file_content,json=fileContent,proto3,oneof"`
}

type CacheEntry_GithubTree struct {
	GithubTree *GitHubTree `protobuf:"bytes,14,opt,name=github_tree,json=githubTree,proto3,oneof"`
}

type CacheEntry_NpmPackage struct {
	NpmPackage *NpmPackage `protobuf:"bytes,15,opt,name=npm_package,json=npmPackage,proto3,oneof"`
}

type CacheEntry_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,16,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*CacheEntry_StringValue) isCacheEntry_Value() {}

func (*CacheEntry_BoolValue) isCacheEntry_Value() {}

func (*CacheEntry_StringList) isCacheEntry_Value() {}

func (*CacheEntry_FileContent) isCacheEntry_Value() {}

func (*CacheEntry_GithubTree) isCacheEntry_Value() {}

func (*CacheEntry_NpmPackage) isCacheEntry_Value() {}

func (*CacheEntry_BytesValue) isCacheEntry_Value() {}

// StringList is a repeated string field wrapper for use in oneof.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_internal_cache_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{2}
}

func (x *StringList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// FileContent stores the [2]string used by gh:file:* entries.
type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_internal_cache_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{3}
}

func (x *FileContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileContent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// GitHubTree mirrors the gh.GitHubTree struct.
type GitHubTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Items         []*GitHubTreeItem      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubTree) Reset() {
	*x = GitHubTree{}
	mi := &file_internal_cache_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubTree) ProtoMessage() {}

func (x *GitHubTree) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubTree.ProtoReflect.Descriptor instead.
func (*GitHubTree) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{4}
}

func (x *GitHubTree) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *GitHubTree) GetItems() []*GitHubTreeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GitHubTree) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// GitHubTreeItem mirrors the gh.GitHubTreeItem struct.
type GitHubTreeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "blob" or "tree"
	Sha           string                 `protobuf:"bytes,4,opt,name=sha,proto3" json:"sha,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubTreeItem) Reset() {
	*x = GitHubTreeItem{}
	mi := &file_internal_cache_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubTreeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubTreeItem) ProtoMessage() {}

func (x *GitHubTreeItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubTreeItem.ProtoReflect.Descriptor instead.
func (*GitHubTreeItem) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GitHubTreeItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GitHubTreeItem) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GitHubTreeItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GitHubTreeItem) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *GitHubTreeItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// NpmPackage mirrors the registry.NpmPackage struct.
type NpmPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Versions      map[string]*NpmVersion `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DistTags      map[string]string      `protobuf:"bytes,3,rep,name=dist_tags,json=distTags,proto3" json:"dist_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpmPackage) Reset() {
	*x = NpmPackage{}
	mi := &file_internal_cache_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpmPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmPackage) ProtoMessage() {}

func (x *NpmPackage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmPackage.ProtoReflect.Descriptor instead.
func (*NpmPackage) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{6}
}

func (x *NpmPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpmPackage) GetVersions() map[string]*NpmVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *NpmPackage) GetDistTags() map[string]string {
	if x != nil {
		return x.DistTags
	}
	return nil
}

// NpmVersion mirrors the registry.NpmVersion struct.
type NpmVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tarball       string                 `protobuf:"bytes,3,opt,name=tarball,proto3" json:"tarball,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpmVersion) Reset() {
	*x = NpmVersion{}
	mi := &file_internal_cache_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpmVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmVersion) ProtoMessage() {}

func (x *NpmVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cache_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmVersion.ProtoReflect.Descriptor instead.
func (*NpmVersion) Descriptor() ([]byte, []int) {
	return file_internal_cache_cache_proto_rawDescGZIP(), []int{7}
}

func (x *NpmVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpmVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NpmVersion) GetTarball() string {
	if x != nil {
		return x.Tarball
	}
	return ""
}

var File_internal_cache_cache_proto protoreflect.FileDescriptor

const file_internal_cache_cache_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/cache/cache.proto\x12\x05cache\"8\n" +
	"\tCacheFile\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.cache.CacheEntryR\aentries\"\x90\x03\n" +
	"\n" +
	"CacheEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\rexpiration_ns\x18\x02 \x01(\x03R\fexpirationNs\x12#\n" +
	"\fstring_value\x18\n" +
	" \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\v \x01(\bH\x00R\tboolValue\x124\n" +
	"\vstring_list\x18\f \x01(\v2\x11.cache.StringListH\x00R\n" +
	"stringList\x127\n" +
	"\ffile_content\x18\r \x01(\v2\x12.cache.FileContentH\x00R\vfileContent\x124\n" +
	"\vgithub_tree\x18\x0e \x01(\v2\x11.cache.GitHubTreeH\x00R\n" +
	"githubTree\x124\n" +
	"\vnpm_package\x18\x0f \x01(\v2\x11.cache.NpmPackageH\x00R\n" +
	"npmPackage\x12!\n" +
	"\vbytes_value\x18\x10 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\"\n" +
	"\n" +
	"StringList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"J\n" +
	"\vFileContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"i\n" +
	"\n" +
	"GitHubTree\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.cache.GitHubTreeItemR\x05items\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"r\n" +
	"\x0eGitHubTreeItem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\tR\x03sha\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\xa8\x02\n" +
	"\n" +
	"NpmPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\bversions\x18\x02 \x03(\v2\x1f.cache.NpmPackage.VersionsEntryR\bversions\x12<\n" +
	"\tdist_tags\x18\x03 \x03(\v2\x1f.cache.NpmPackage.DistTagsEntryR\bdistTags\x1aN\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cache.NpmVersionR\x05value:\x028\x01\x1a;\n" +
	"\rDistTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\n" +
	"NpmVersion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\atarball\x18\x03 \x01(\tR\atarballB\x16Z\x14cxcdn/internal/cacheb\x06proto3"

var (
	file_internal_cache_cache_proto_rawDescOnce sync.Once
	file_internal_cache_cache_proto_rawDescData []byte
)

func file_internal_cache_cache_proto_rawDescGZIP() []byte {
	file_internal_cache_cache_proto_rawDescOnce.Do(func() {
		file_internal_cache_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_cache_cache_proto_rawDesc), len(file_internal_cache_cache_proto_rawDesc)))
	})
	return file_internal_cache_cache_proto_rawDescData
}

var file_internal_cache_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_cache_cache_proto_goTypes = []any{
	(*CacheFile)(nil),      // 0: cache.CacheFile
	(*CacheEntry)(nil),     // 1: cache.CacheEntry
	(*StringList)(nil),     // 2: cache.StringList
	(*FileContent)(nil),    // 3: cache.FileContent
	(*GitHubTree)(nil),     // 4: cache.GitHubTree
	(*GitHubTreeItem)(nil), // 5: cache.GitHubTreeItem
	(*NpmPackage)(nil),     // 6: cache.NpmPackage
	(*NpmVersion)(nil),     // 7: cache.NpmVersion
	nil,                    // 8: cache.NpmPackage.VersionsEntry
	nil,                    // 9: cache.NpmPackage.DistTagsEntry
}
var file_internal_cache_cache_proto_depIdxs = []int32{
	1, // 0: cache.CacheFile.entries:type_name -> cache.CacheEntry
	2, // 1: cache.CacheEntry.string_list:type_name -> cache.StringList
	3, // 2: cache.CacheEntry.file_content:type_name -> cache.FileContent
	4, // 3: cache.CacheEntry.github_tree:type_name -> cache.GitHubTree
	6, // 4: cache.CacheEntry.npm_package:type_name -> cache.NpmPackage
	5, // 5: cache.GitHubTree.items:type_name -> cache.GitHubTreeItem
	8, // 6: cache.NpmPackage.versions:type_name -> cache.NpmPackage.VersionsEntry
	9, // 7: cache.NpmPackage.dist_tags:type_name -> cache.NpmPackage.DistTagsEntry
	7, // 8: cache.NpmPackage.VersionsEntry.value:type_name -> cache.NpmVersion
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_internal_cache_cache_proto_init() }
func file_internal_cache_cache_proto_init() {
	if File_internal_cache_cache_proto != nil {
		return
	}
	file_internal_cache_cache_proto_msgTypes[1].OneofWrappers = []any{
		(*CacheEntry_StringValue)(nil),
		(*CacheEntry_BoolValue)(nil),
		(*CacheEntry_StringList)(nil),
		(*CacheEntry_FileContent)(nil),
		(*CacheEntry_GithubTree)(nil),
		(*CacheEntry_NpmPackage)(nil),
		(*CacheEntry_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_cache_cache_proto_rawDesc), len(file_internal_cache_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_cache_cache_proto_goTypes,
		DependencyIndexes: file_internal_cache_cache_proto_depIdxs,
		MessageInfos:      file_internal_cache_cache_proto_msgTypes,
	}.Build()
	File_internal_cache_cache_proto = out.File
	file_internal_cache_cache_proto_goTypes = nil
	file_internal_cache_cache_proto_depIdxs = nil
}
